Maqalat_app/urls.py
from django.urls import path
from . import views
app_name='Maqalat'
urlpatterns=[
    path('detail/<slug:slug>',views.post_detail,name='detail'),
    path('list',views.post_list,name='Article List'),
    path('category/<int:pk>',views.category_list,name='category_list'),
    path('search/',views.search,name='article_search'),
    path('contact',views.Contact_us,name='contact_us'),


]

accounts_app/urls.py
from django.urls import path
from . import views
app_name='account'
urlpatterns = [
    path('login', views.user_login,name='login'),
    path('logout', views.user_logout, name='logout'),
    path('register', views.user_register, name='register')
]

djangoproject/urls.py
from django.contrib import admin
from django.urls import path
from  django.urls import path,include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("home_app.urls")),
    path('', include('accounts_app.urls')),
    path('', include('Maqalat_app.urls')),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home_app/urls.py
from  django.urls import path
from . import views
app_name='home'
urlpatterns=[
    path('',views.home, name='home'),
    path('sidbar',views.sidbar,name='sidbar')
]

Maqalat_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify



class Category(models.Model):
    title=models.CharField(max_length=30,unique=True)
    created=models.DateTimeField(auto_now_add=True)
    

  

    def __str__(self):
        return self.title





class Article(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    category=models.ManyToManyField(Category,related_name='articles')
    title=models.CharField(max_length=50)
    body=models.TextField()
    image=models.ImageField(upload_to='images/articl')
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    slug=models.SlugField(unique=True,blank=True)

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        self.slug=slugify(self.title)
        super(Article, self).save()


    def get_absolute_ulr(self):
        return reverse('Maqalat:detail',kwargs={'slug':self.slug})


    def __str__(self):
        return f'{self.title} - {self.body[:30]}'




class Comment(models.Model):
    article=models.ForeignKey(Article,on_delete=models.CASCADE,related_name='comment')
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    created=models.DateTimeField(auto_now_add=True)
    text=models.TextField()
    patern=models.ForeignKey('self',null=True,blank=True,on_delete=models.CASCADE ,related_name='repleis')


    class Meta:
        ordering=['-created',]


    def __str__(self):
        return f'{self.user} - {self.text[:15]}'

accounts_app/models.py
from django.db import models
from django.contrib.auth.models import User



class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    user_code=models.IntegerField()
    image=models.ImageField(upload_to='profile/image',blank=True,null=True)

    def __str__(self):
        return self.user.username






# Create your models here.

home_app/models.py
from django.db import models

# Create your models here.

Maqalat_app/views.py
from django.shortcuts import render
from Maqalat_app.models import Article,Category
from django.core.paginator import Paginator



def post_detail(request,slug):
    article=Article.objects.get(slug=slug)
    return render(request, 'Maqalat_app/post-details.html',{'article':article})





def post_list(request):
     article=Article.objects.all()
     paginator=Paginator(article,2)
     page_number=request.GET.get('page')
     article_list=paginator.get_page(page_number)
     return render(request,'Maqalat_app/post_list.html',{'articles':article_list})



def category_list(request,pk=None):
    category= Category.objects.get(id=pk)
    article=category.articles.all()
    return render(request,'Maqalat_app/post_list.html',{'article':article})

def search(request):
    q = request.GET.get('q')
    article = Article.objects.filter(title__icontains=q)
    page_num = request.GET.get('page')
    paginator = Paginator(article, 1)
    articles = paginator.get_page(page_num)
    return render(request, 'Maqalat_app/post_list.html', {'articles': articles})


def Contact_us(request):
    return render(request,'Maqalat_app/contact_us.html',{})

accounts_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User


def user_login(request):
    if request.user.is_authenticated == True:
        return redirect('home:home')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home:home')
        else:
            return render(request, 'accounts_app/error page.html')

    return render(request, 'accounts_app/login.html', {})


def user_logout(request):
    logout(request)
    return redirect('home:home')


def user_register(request):
    if request.user.is_authenticated == True:
        return redirect('home:home')
    context = {'errors': []}

    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        if password1 != password2:
            context['errors'].append('The passwords are not same')
            return render(request, "accounts_app/register.html", context)
            # if User.objects.get(username=username):
            #     context['errors'].append('This username is exists')
            #     return render(request, "accounts_app/register.html", context)

        User.objects.create(username=username, email=email, password=password1)

        return redirect('account:login')
    return render(request, "accounts_app/register.html", {})

home_app/views.py
from django.shortcuts import render
from Maqalat_app.models import Article

def home(request):
    articles=Article.objects.all()
    recent_post=Article.objects.all().order_by('-updated','-created')
    return render(request, 'home_app/home.html', {'article':articles})
# Create your views here.



def sidbar(request):
    render(request,'include/sidebar.html',{})

Maqalat_app/templates/Maqalat_app/About.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
   About Us
{% endblock %}

{% block content %}
      <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>about us</h4>
                <h2>more about us!</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>

    <!-- Banner Ends Here -->


    <section class="about-us">
      <div class="container">

        <div class="row">
          <div class="col-lg-12">
            <img src="assets/images/about-us.jpg" alt="">
            <p>Please tell your friends about TemplateMo website. Thank you. You can browse through different categories of templates such as <a rel="nofollow" href="https://templatemo.com/tag/business" target="_parent">business</a>, <a rel="nofollow" href="https://templatemo.com/tag/portfolio" target="_parent">portfolio</a>, <a rel="nofollow" href="https://templatemo.com/tag/restaurant" target="_parent">restaurant</a>, etc. Pellentesque quis luctus libero. Maecenas pretium molestie erat, ac tincidunt leo gravida ac. Cras ullamcorper eu ipsum eu sollicitudin. Fusce vitae commodo turpis. Integer ullamcorper purus nec justo mollis fermentum. Nunc imperdiet erat nec lacinia laoreet. <br><br>Maecenas faucibus ullamcorper felis vitae finibus. Nullam at quam ut lacus aliquam tempor vel sed ipsum. Donec pellentesque tincidunt imperdiet. Mauris sit amet justo vulputate, cursus massa congue, vestibulum odio. Aenean elit nunc, gravida in erat sit amet, feugiat viverra leo. Phasellus interdum, diam commodo egestas rhoncus, turpis nisi consectetur nibh, in vehicula eros orci vel neque.</p>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-6">
          <h4>Two-One Donec porttitor augue</h4>
          	<p>Quisque bibendum cursus viverra. Mauris at ex ipsum. Aenean condimentum urna nisl, eget interdum ante euismod vel. Aliquam at metus sit amet nunc dapibus posuere.</p>
          </div>
          <div class="col-lg-6">
          <h4>Two-Two Donec porttitor augue</h4>
          	<p>Maecenas et metus nisl. Morbi ac interdum metus. Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-4 col-md-6">
          <h4>1-03 Donec porttitor augue</h4>
          	<p>Quisque bibendum cursus viverra. Mauris at ex ipsum. Aenean condimentum urna nisl, eget interdum ante euismod vel. Aliquam at metus sit amet nunc dapibus posuere.</p>
          </div>
          <div class="col-lg-4 col-md-6">
          <h4>2-03 Donec porttitor augue</h4>
          	<p>Maecenas et metus nisl. Morbi ac interdum metus. Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
          <div class="col-lg-4">
          <h4>3-03 Donec porttitor augue</h4>
          	<p>Maecenas et metus nisl. Morbi ac interdum metus. Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
        </div>


        <div class="row">
          <div class="col-lg-3 col-md-6">
          <h4>01 Four Columns</h4>
          	<p>Mauris at ex ipsum. Aenean condimentum urna nisl, eget interdum ante euismod vel. Aliquam at metus sit amet nunc dapibus posuere.</p>
          </div>
          <div class="col-lg-3 col-md-6">
          <h4>02 Four Columns</h4>
          	<p>Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
          <div class="col-lg-3 col-md-6">
          <h4>03 Four Columns</h4>
          	<p>Morbi ac interdum metus. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
          <div class="col-lg-3 col-md-6">
          <h4>04 Four Columns</h4>
          	<p>Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-12">
            <ul class="social-icons">
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-behance"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>


      </div>
    </section>

{% endblock %}

Maqalat_app/templates/Maqalat_app/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Article List
{% endblock %}
{% block content %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>Recent Posts</h4>
                            <h2>Our Recent Article List</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <section class="blog-posts grid-system">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            {% for item in articles %}
                                <div class="col-lg-6">
                                    <div class="blog-post">
                                        <div class="blog-thumb">
                                            <img src="{{ item.image.url }}" alt="">
                                        </div>
                                        <div class="down-content">
                                            <span>Lifestyle</span>
                                            <a href="{{ item.get_absolute_ulr }}"><h4>{{ item.title }}</h4></a>
                                            <ul class="post-info">
                                                <li><a href="#">{{ item.author.get_full_name }}</a></li>
                                                <li><a href="#">{{ item.created }}</a></li>
                                                <li><a href="#">12 Comments</a></li>
                                            </ul>
                                            <p>{{ item.body }}</p>
                                            <div class="post-options">
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <ul class="post-tags">
                                                            <li><i class="fa fa-tags"></i></li>
                                                            <li><a href="#">Best Templates</a>,</li>
                                                            <li><a href="#">TemplateMo</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            {% if articles.has_other_pages %}
                                <div class="col-lg-12">
                                    <ul class="page-numbers">
                                        {% if articles.has_previous %}
                                            <li><a href="?page={{ articles.previous_page_number }}"><i
                                                    class="fa fa-angle-double-left"></i></a></li>
                                        {% endif %}
                                        {% for i in articles.paginator.page_range %}
                                            {% if article.number == i %}
                                                <li class="active"><a href="?page={{ i }}{% if request.Get.q %}&q={{ request.Get.q }}{% endif %}">{{ i }}</a></li>
                                            {% else %}
                                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if articles.has_next %}
                                            <li><a href="?page={{ articles.next_page_number }}{% if request.Get.q %}&q={{ request.Get.q }}{% endif %}"><i
                                                    class="fa fa-angle-double-right"></i></a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% include 'include/sidebar.html' %}
            </div>
        </div>
    </section>
{% endblock %}

accounts_app/templates/accounts_app/error page.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <title>Error</title>
</head>
<body>
 <h1>
     This is a wrong way
 </h1>
</body>
</html>

accounts_app/templates/accounts_app/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href=" {% static 'login/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'login/images/img-01.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form" method="post">{% csrf_token %}

					<span class="login100-form-title">
						Member Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "enter username">
						<input class="input100" type="text" name="username" placeholder="username">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user" aria-hidden="true" style='font-size:18px'></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true" style='font-size:18px'></i>
						</span>
					</div>
                    <div class="contact100-form-checkbox">
						<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
						<label class="label-checkbox100" for="ckb1">
							Remember me
						</label>
					</div>
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href="{% url 'account:register' %}">
							Create your Account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	
	

	
<!--===============================================================================================-->	
	<script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static "login/vendor/select2/select2.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('{% static "login/.js-tilt" %}').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'login/js/main.js' %}"></script>

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

<head>


{% include 'include/header.refrens.html' %}
</head>

<body>

<!-- ***** Preloader Start ***** -->
<div id="preloader">
    <div class="jumper">
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>
<!-- ***** Preloader End ***** -->

<!-- Header -->

{% include 'include/header.html' %}
{% block content %}

{% endblock %}





{% include 'include/footer.html' %}
{% include 'include/footer.refrens.html' %}





</body>
</html>

templates/include/footer.html
{% load static %}
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="social-icons">
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Behance</a></li>
                    <li><a href="#">Linkedin</a></li>
                    <li><a href="#">Dribbble</a></li>
                </ul>
            </div>
            <div class="col-lg-12">
                <div class="copyright-text">
                    <p>Copyright 2020 Stand Blog Co.

                        | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/include/footer.refrens.html
{% load static %}
<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Additional Scripts -->
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/owl.js' %}"></script>
<script src="{% static 'js/slick.js' %}"></script>
<script src="{% static 'js/isotope.js' %}"></script>
<script src="{% static 'js/accordions.js' %}"></script>

<script language="text/Javascript">
    cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
    function clearField(t) {                   //declaring the array outside of the
        if (!cleared[t.id]) {                      // function makes it static and global
            cleared[t.id] = 1;  // you could use true and false, but that's more typing
            t.value = '';         // with more chance of typos
            t.style.color = '#fff';
        }
    }
</script>

templates/include/header.html
{% load static %}
<header class="">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="home.html"><h2>Stand Blog<em>.</em></h2></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item {% if request.resolver_match.url_name == 'home' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'home:home' %}">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About Us</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'Article List' %} active  {% endif %}">
                        <a class="nav-link" href="{% url 'Maqalat:Article List' %}">Article List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">Post Details</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Maqalat:contact_us' %}">Contact Us</a>
                    </li>
                    </li>
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                            <div class="d-flex">
                                {% if request.user.firt_name %}
                                    <img src="{{ user.profile.image.url }}" width="25px" height="25px"
                                         style="border-radius: 100%">

                                    <a class="nav-link" href="">{{ request.user.first_name }}</a>
                                {% else %}
                                    <img src="{{ user.profile.image.url }}" width="25px" height="25px"
                                         style="border-radius: 100%">
                                    <a class="nav-link" href=' '>{{ request.user.username }}</a>

                                {% endif %}
                                <a class="nav-link" href=' {% url "account:logout" %} '>logout</a>

                            </div>
                        {% else %}
                            <div class="d-flex">
                                <a class="nav-link" href=' {% url "account:login" %} '>login</a><span
                                    class="mt-2">/</span>
                                <a class="nav-link" href='{% url 'account:register' %} '>register</a>
                            </div>

                        {% endif %}

                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/include/header.refrens.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="TemplateMo">
<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
      rel="stylesheet">

<title>{% block title %}{% endblock %}</title>

<!-- Bootstrap core CSS -->
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


<!-- Additional CSS Files -->
<link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
<link rel="stylesheet" href="{% static 'css/templatemo-stand-blog.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.css' %}">

templates/include/sidebar.html
  <div class="col-lg-4">
                <div class="sidebar">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="sidebar-item search">
                                <form id="search_form" name="gs" method="GET" action="{% url 'Maqalat:article_search' %}">
                                    <input type="text" name="q" class="searchText" placeholder="type to search..."
                                           autocomplete="on">
                                </form>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item recent-posts">
                                <div class="sidebar-heading">
                                    <h2>Recent Posts</h2>
                                </div>
                                <div class="content">
                                    <ul>
                                       {% for item in recent_post %}
                                        <li><a href="{{ item.get_absolute_ulr }}">
                                            <h5>{{ item.title }}</h5>
                                            <span>{{ item.created }}</span>
                                        </a></li>
                                       {% endfor %}


                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item categories">
                                <div class="sidebar-heading">
                                    <h2>Categories</h2>
                                </div>
                                <div class="content">
                                    <ul>
                                       {% for cat in category  %}
                                            <li><a href="{% url 'Maqalat:category_list' cat.id %}">{{ cat.title }}</a></li>

                                       {% endfor %}


                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item tags">
                                <div class="sidebar-heading">
                                    <h2>Tag Clouds</h2>
                                </div>
                                <div class="content">
                                    <ul>
                                        <li><a href="#">Lifestyle</a></li>
                                        <li><a href="#">Creative</a></li>
                                        <li><a href="#">HTML5</a></li>
                                        <li><a href="#">Inspiration</a></li>
                                        <li><a href="#">Motivation</a></li>
                                        <li><a href="#">PSD</a></li>
                                        <li><a href="#">Responsive</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>